[package]
name = "samurai"
version = "0.1.0"
authors = ["descawed <samurai@descawed.com>"]
edition = "2021"
description = "Tools for working with the files of the game (Way of the) Samurai"
repository = "https://github.com/descawed/samurai"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "~1.0.82"
binrw = "~0.13.3"
clap = "~4.5.4"
encoding_rs = "~0.8.34"
pathdiff = "~0.2.1"
walkdir = "~2.5.0"
log = "0.4.21"
